application: inorgbisect
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico

- url: /html
  static_dir: assets/html

- url: /img
  static_dir: assets/img

- url: /bs
  static_dir: assets/bootstrap

- url: /js
  static_dir: assets/js

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"